### ISSUE TITLE
Media from Pandora is no longer paused when switching tabs

### ISSUE THREAD

**Issue by giantspeck** [NDevTK/AutoPause#14] opened 2021-10-12 07:18 UTC
After updating to Firefox 93.0, the extension no longer automatically pauses Pandora Radio when viewing media in other tabs.

I have unsuccessfully attempted to remedy this issue by:  

- restarting Firefox
- logging out of Pandora and clearing its cache
- creating a new Firefox profile
- updating to Firefox Nightly (95.x)

**Comment by NDevTK** [comment] 2021-10-12 08:55
Thanks for the report, I will look into this now.

**Comment by NDevTK** [comment] 2021-10-12 10:07
Unable to verify :(

Permission: https://*.pandora.com/* https://*.youtube.com/*
Firefox Version: 93.0

Test URL: https://www.pandora.com/station/play/97785068763745031

Paused on going to
https://www.youtube.com/watch?v=DLzxrzFCyOs

**Comment by NDevTK** [comment] 2021-10-13 19:22
To confirm both .playbackRate = 0; and .pause(); dont pause it.
And when you do document.getElementsByTagName("audio") its the only audio element on the page?

It maybe that its live and does not support pausing 2.7 also has a tab mute feature in the options page that may also work,
And waste bandwidth.

**Comment by giantspeck** [comment] 2021-10-13 19:33
Neither of them paused the audio.

Running `document.getElementsByTagName("audio")` by itself returns

```
← HTMLCollection { 0: audio , length: 1 }
```

**Comment by giantspeck** [comment] 2021-10-13 19:36
The audio *can* be paused with other methods, though.  

I use the [Pandora Media Session](https://github.com/snaphat/pandora_media_session) extension to enable the use of my keyboard's media keys (because Pandora does not do this natively on Firefox).  It simulates click actions to play/pause audio and skip tracks.

_(I made sure this extension was not enabled when testing the functions above.)_

**Comment by giantspeck** [comment] 2021-10-13 20:37
It resumes to the same time.

I'm perfectly content with the auto tab mute feature, though.  I don't think we need to make your extension more complicated just to support one site that not everyone uses.  The extension works fine for pretty much any other website I've tried it on.

Thank you for your help.

**Comment by NDevTK** [comment] 2021-10-13 21:42
It should be supported its strange because if the .playbackRate is 0 and stays 0 the audio should never play.
If .currentTime is changing with a playbackRate of 0 and since this after a browser update it may be a bug in firefox.
By the error it seems that the normal .pause() has been overridden.

**Comment by NDevTK** [comment] 2021-10-13 22:40
Im aware the current tab mute feature is broken i will try to fix it.

**Comment by NDevTK** [comment] 2022-03-24 01:41
Per https://github.com/NDevTK/AutoPause/issues/14#issuecomment-942701915 as the tab mute feature is on the webstore and I dont have a access to Pandora... I will close this issue now please reopen if still its wanted.

**Comment by NDevTK** [comment] 2022-03-24 19:46
Currently theirs a feature to mark a tab as background audio resuming I think I might add a mute only option so that live media works correctly.

**Comment by giantspeck** [comment] 2022-03-26 23:24
Sorry for the late response, but I've actually been able to use AutoPause with Pandora for a few weeks ago.  I'm not sure if it was a Firefox update or the latest version of AutoPause that fixed the issue, but the issue isn't there anymore.

**Comment by NDevTK** [comment] 2022-03-26 23:54
No idea what fixed it but glad its working now :)
Closing as unreproducible.

**Closed by NDevTK** 2022-03-26 23:54 UTC
Labels: bug, unreproducible
