### ISSUE TITLE
Netflix Video Not Working: Blackscreen

### ISSUE THREAD

**Issue by DecodedMonkey** [NDevTK/AutoPause#31] opened 2022-10-06 22:49 UTC
**Describe the bug**
When installed and enabled, it causes Netflix to not play video.
Audio still plays, just no video output.

**To Reproduce**
1. Install Add-on
2. Play Video on Netflix
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox 105.0.2 (64-bit)

**Extension configuration**
- Version of extension: 2.7.6
- Options changed: None

**Browser configuration**
 - Flag changes: None
 - Other extensions: None
 - Browser configuration: None

**Comment by NDevTK** [comment] 2022-10-06 22:58
Thanks for the report :)
I don't have a netflix subscription.

When you press F12 while watching a video is there any errors?
Does this affect any other website?

**Comment by DecodedMonkey** [comment] 2022-10-06 23:06
Uncaught (in promise) DOMException: Node.removeChild: The node to be removed is not a child of this node

This error disappears when disabling the extension, so I think it is being caused by AutoPause.

**Comment by NDevTK** [comment] 2022-10-06 23:23
Without the extension and a video playing...
Does this play the media?
[...document.getElementsByTagName('video')].forEach(v => {v.playbackRate = 0});
Does this pause the media?
[...document.getElementsByTagName('video')].forEach(v => {v.playbackRate = 1}) ;


Does this fix it? https://github.com/NDevTK/AutoPause/actions/runs/3201095010

**Comment by NDevTK** [comment] 2022-10-06 23:46
Since this issue seems to be with the extension preventing .play()
I added error handling does https://github.com/NDevTK/AutoPause/actions/runs/3201219856 work?
If you need help testing it pls say :)

**Comment by DecodedMonkey** [comment] 2022-10-06 23:58
The media does Play and pause, using the code snippets.

[3201219856](https://github.com/NDevTK/AutoPause/actions/runs/3201219856) does not seem to fix the issue.

Though, I no longer see any errors in Firefox dev tools.

**Comment by DecodedMonkey** [comment] 2022-10-06 23:59
I take that back the error is still there had to refresh a few times though. Not sure what that is about.

I am doing this testing in a clean version of Firefox Dev Edtion

**Comment by NDevTK** [comment] 2022-10-07 00:00
Did you try https://github.com/NDevTK/AutoPause/actions/runs/3201095010 that should remove the code injection part for netflix.

**Comment by DecodedMonkey** [comment] 2022-10-07 00:03
[3201095010](https://github.com/NDevTK/AutoPause/actions/runs/3201095010)

Does fix the issue.

**Comment by NDevTK** [comment] 2022-10-07 00:07
🎉Okay guess the issue is with WindowScript.js
Does the extension still pause the media?

**Comment by DecodedMonkey** [comment] 2022-10-07 00:09
Yes, seems to be working as intend.

**Comment by NDevTK** [comment] 2022-10-07 00:15
Should now be fixed in master https://github.com/NDevTK/AutoPause/actions/runs/3201329494
Will leave open until theirs a Firefox release.

**Comment by NDevTK** [comment] 2022-10-07 03:16
If all goes well I will publish https://github.com/NDevTK/AutoPause/releases/tag/2.7.7 in less then 24 hours.
It also includes performance improvements since there was a logic issue with the content script..
Also it now pauses hidden muted media.

**Comment by NDevTK** [comment] 2022-10-08 01:58
Fixed in version 2.7.7 and published on Firefox.

**Closed by NDevTK** 2022-10-08 01:58 UTC
Labels: bug
